function myFunction(arr, number) {
    if (!arr) throw new ReferenceError("'arr' √© um par√¢metro obrigat√≥rio.");
    if (!number) throw new ReferenceError("'number' √© um par√¢metro obrigat√≥rio.");
    if (typeof arr !== "object")
        throw new TypeError("O par√¢metro 'arr' deve ser do tipo 'objeto'.");
    if (typeof number !== "number")
        throw new TypeError("O par√¢metro 'number' deve ser do tipo 'number'.");
    if (arr.length !== number)
        throw new RangeError(
            "O tamanho do par√¢metro 'arr' dever ser igual ao valor do par√¢metro 'number'."
        );

    return `O array tem ${number} ${number === 1 ? "elemento" : "elementos"}.`;
}

const tests = [
    { arr: undefined, num: undefined, expectedErr: ReferenceError },
    { arr: "a", num: undefined, expectedErr: ReferenceError },
    { arr: "a", num: 1, expectedErr: TypeError },
    {
        arr: ["a"],
        num: "1",
        expectedErr: RangeError,
    },
    {
        arr: ["a"],
        num: 2,
        expectedErr: RangeError,
    },
    {
        arr: ["a"],
        num: 1,
        expectedErr: undefined,
    },
    {
        arr: ["a", "b"],
        num: 2,
        expectedErr: undefined,
    },
];

console.log("Testando a fun√ß√£o myFunction\n");
tests.map((test, index) => {
    console.log(`-----------------------`);
    console.log(`‚û° Teste: ${index + 1}`);
    console.log("arr: ", test.arr);
    console.log("number: ", test.num);
    let err = undefined;
    try {
        const result = myFunction(test.arr, test.num);
        console.log("Resultado da Fun√ß√£o:", result);
    } catch (e) {
        err = e;
        if (e instanceof ReferenceError) {
            console.log(`ERRO: Est√£o faltando par√¢metros:`);
        } else if (e instanceof TypeError) {
            console.log(`ERRO: Os par√¢metros n√£o s√£o do tipo esperado:`);
        } else if (e instanceof RangeError) {
            console.log(`ERRO: Os par√¢metros s√£o inconsistentes entre si:`);
        } else {
            console.log(`ERRO: Erro n√£o esperado:`);
        }
        console.log("Mensagem original do erro: ", err.message);
    } finally {
        if (err === test.expectedErr || err instanceof test.expectedErr) {
            console.log(`‚úî O Teste ${index + 1} passou`);
        } else {
            console.log(`‚ùå O Teste ${index + 1} N√ÉO passou`);
            console.log("EXPECTED ERROR:", test.expectedErr);
            console.log("RETURNED ERROR:", err ? err.name : err);
        }
        console.log(`\n\n`);
    }
});

console.log("Fim dos testes üòÅ");